name: geopub
channels:
  - conda-forge
dependencies:
  - python=3.11
  - gdal
  - geopandas
  - matplotlib
  - lxml
  - openpyxl
  - pyyaml
  - typer
  - requests
  - python-dotenv
  - jsonschema
  - pytest
  - ruff
  - pip
  - pip:
      - -e .
